root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  
  delay = 200 
  rerun = true
  rerun_delay = 200
  kill_delay = "500ms"
  stop_on_error = true 

  include_ext = ["go", "tpl", "tmpl", "html", "eml"]
  exclude_regex = ["_test.go"]

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true 

[screen]
  clear_on_rebuild = true 
